-- migrate:up
ALTER TABLE projects
	ALTER COLUMN image TYPE VARCHAR(255);

ALTER TABLE organizers
	ALTER COLUMN image TYPE VARCHAR(255);

ALTER TABLE partners
	ALTER COLUMN image TYPE VARCHAR(255);

ALTER TABLE merch
	ALTER COLUMN image TYPE VARCHAR(255);

-- migrate:down
ALTER TABLE projects
	ALTER COLUMN image TYPE BYTEA;

ALTER TABLE organizers
	ALTER COLUMN image TYPE BYTEA;

ALTER TABLE partners
	ALTER COLUMN image TYPE BYTEA;

ALTER TABLE merch
	ALTER COLUMN image TYPE BYTEA;
