-- migrate:up
ALTER TABLE projects
	ALTER COLUMN image TYPE VARCHAR(255);

ALTER TABLE organizers
	ALTER COLUMN image TYPE VARCHAR(255);

ALTER TABLE partners
	ALTER COLUMN image TYPE VARCHAR(255);

ALTER TABLE merch
	ALTER COLUMN image TYPE VARCHAR(255);

-- migrate:down
ALTER TABLE projects
	DROP COLUMN image,
	ADD COLUMN image BYTEA;

ALTER TABLE organizers
	DROP COLUMN image,
	ADD COLUMN image BYTEA;

ALTER TABLE partners
	DROP COLUMN image,
	ADD COLUMN image BYTEA;

ALTER TABLE merch
	DROP COLUMN image,
	ADD COLUMN image BYTEA;
